[tool.poetry]
name = "fly-in"
version = "1.0.0"
description = "Node-Drone pathfinding"
authors = ["agalvan-"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.0"
pydantic = "^2.6.0"
pygame = ">=2.6.1"
rich = "^13.7.0"
questionary = "^2.0.1" 

[tool.poetry.group.dev.dependencies]
build = "^1.2.2"
flake8 = "^7.0.0"
flake8-pyproject = "^1.2.4"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
exclude = [
    ".git",
    "venv",
    ".venv",
    "__pycache__",
]
max-line-length = 88

[tool.mypy]
exclude = ["venv", ".venv"]
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
